-- First, remove the table if it exists
drop table if exists profile;

-- Create the table anew
create table profile (
  id INTEGER primary key generated by default as identity,
  name  varchar(50)
);