-- First, remove the table if it exists
drop table if exists profiles;

-- Create the table anew
create table profiles (
  id INTEGER primary key generated by default as identity,
  name  varchar(50)
);