-- First, remove the table if it exists
drop table if exists diaries;

-- Create the table anew
create table diaries (
  id INTEGER primary key generated by default as identity,
  name  varchar(50) NOT NULL,
  diarydate TEXT NOT NULL, 
  medication TEXT,
  weight TEXT,
  diet TEXT,
  allergies TEXT,
  body TEXT,
  other TEXT
);

